### ISSUE TITLE
!default in scss is not properly colored

### ISSUE THREAD

**Issue by hanakin** [tobiasalthoff/vscode-atom-material-theme#14]
currently, there is no color assigned to the `!default` scss variable flag. in vscode, in atom, this should be rendered purple the same as `function`

**Comment by tobiasalthoff** [comment]
First of all, thanks for your pull request! You are right. Some syntax colors are not exactly like Atom material. But Atom Material is also not consistent enough in many places. I will have a look at the color scheme of the current Atom Material Syntax version in the near future. Until then, can you please make a separate pull request of this issue here, just for the SCSS part? Thanks!

**Comment by hanakin** [comment]
Updated pull request to just fix the scss issues

**Comment by tobiasalthoff** [comment]
Thanks. Pull request merged and new version 1.10.6 is publishing → update should be available in a few minutes!
